DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK (
                      ID BIGINT NOT NULL AUTO_INCREMENT,
                      STATUS VARCHAR(64) NOT NULL,
                      TITLE VARCHAR(128) NOT NULL,
                      DESCRIPTION VARCHAR(512) NOT NULL,
                      DUE_DATE DATE,
                      CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
